// <auto-generated />
using System;
using DevOpsAppRepo;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DevOpsAppRepo.Migrations
{
    [DbContext(typeof(DevOpsAppDbContext))]
    partial class DevOpsAppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DevOpsAppRepo.Entities.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("DiscordUsername")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DevOpsAppRepo.Entities.UserEggSnapshot", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<decimal?>("BoostsUsed")
                        .HasColumnType("numeric(20,0)");

                    b.Property<double?>("Cer")
                        .HasColumnType("double precision");

                    b.Property<double?>("CraftingXp")
                        .HasColumnType("double precision");

                    b.Property<double?>("Eb")
                        .HasColumnType("double precision");

                    b.Property<decimal?>("EggsOfProphecy")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("EiUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("GoldenEggsBalance")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("GoldenEggsEarned")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal?>("GoldenEggsSpent")
                        .HasColumnType("numeric(20,0)");

                    b.Property<double?>("Jer")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("LastFetchedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("Mer")
                        .HasColumnType("double precision");

                    b.Property<string>("RawJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<double?>("SoulEggs")
                        .HasColumnType("double precision");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("TruthEggs")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "EiUserId")
                        .IsUnique();

                    b.ToTable("UserEggSnapshots");
                });

            modelBuilder.Entity("DevOpsAppRepo.Entities.UserEggSnapshot", b =>
                {
                    b.HasOne("DevOpsAppRepo.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
