// <auto-generated />
using System;
using DevOpsAppRepo;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DevOpsAppRepo.Migrations
{
    [DbContext(typeof(DevOpsAppDbContext))]
    [Migration("20260209140155_EiUserIdHashed")]
    partial class EiUserIdHashed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DevOpsAppRepo.Entities.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DevOpsAppRepo.Entities.UserEggSnapshot", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<decimal?>("BoostsUsed")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("EiUserIdHash")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastFetchedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RawJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("UserId");

                    b.ToTable("UserEggSnapshots");
                });

            modelBuilder.Entity("DevOpsAppRepo.Entities.UserEggSnapshot", b =>
                {
                    b.HasOne("DevOpsAppRepo.Entities.User", null)
                        .WithOne()
                        .HasForeignKey("DevOpsAppRepo.Entities.UserEggSnapshot", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
