name: Fly DeployClientStaging
on:
  push:
    branches:
      - main
      - Dev
      - Dev2
      - FlyTestStaging
      - databaseUpdate
  pull_request:
    branches:
      - main
      - Dev    # change to main if needed
      - Dev2
      - FlyTestStaging
      - databaseUpdate
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy -c ./fly.staging.toml --remote-only
        working-directory: Client/
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKENCLIENT }}

      - name: Setup K6
        uses: grafana/setup-k6-action@v1
      - name: Run local k6 test
        uses: grafana/run-k6-action@v1
        with:
          path: ./Client/src/K6TestingClient.js
        env:
          K6LOGINTEST_EMAIL: ${{ secrets.K6LOGINTEST_EMAIL }}
          K6LOGINTEST_PASSWORD: ${{ secrets.K6LOGINTEST_PASSWORD }}