name: Fly DeployClientProduction
on:
  workflow_run:
    workflows: ["Fly DeployClientStaging"]
    branches: [main, FlyTestStaging]
    types: [completed]
jobs:
  deploy:
    name: Deploy app    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy -c ./fly.production.toml --remote-only
        working-directory: Client/
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKENCLIENT }}