name: k6 Load Test

on:
  push:
    branches:
      - Dev

jobs:
  run-testClient:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup K6
        uses: grafana/setup-k6-action@v1
      - name: Run local k6 test
        uses: grafana/run-k6-action@v1
        with:
          path: ./DevOpsClient/src/k6TestingClient.js
        env:
          K6LOGINTEST_EMAIL: ${{ secrets.K6LOGINTEST_EMAIL }}
          K6LOGINTEST_PASSWORD: ${{ secrets.K6LOGINTEST_PASSWORD }}
          
  run-testServer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup K6
        uses: grafana/setup-k6-action@v1
      - name: Run local k6 test
        uses: grafana/run-k6-action@v1
        with:
          path: ./Server/Api/DevOpsAppApi/k6Testing.js
        env:
          K6LOGINTEST_EMAIL: ${{ secrets.K6LOGINTEST_EMAIL }}
          K6LOGINTEST_PASSWORD: ${{ secrets.K6LOGINTEST_PASSWORD }}